use SelectoJDE
go

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-------------------------------------------------------------------------------------------
-- Populate the Vendor Master records.
--
-- 24-Jan-2020 R.Lillback Created Initial Version
-- 12-Feb-2020 R.Lillback Changed procedures name from usp_F0401
--------------------------------------------------------------------------------------------
IF EXISTS(SELECT * FROM SYS.objects WHERE TYPE = 'P' AND name = N'usp_F0401_Vendor')
	DROP PROCEDURE dbo.usp_F0401_Vendor
GO

CREATE PROCEDURE dbo.usp_F0401_Vendor
AS
BEGIN
	-- Set up the audit trail
	declare @user nvarchar(10) = N'RLILLBACK';
	declare @pid nvarchar(10) = N'SQLLD';
	declare @jobn nvarchar(10) = N'SQLLD';
	declare @jToday numeric(18,0)= dbo.fn_DateTimeToJulian(GETDATE()); -- Julian Date Today
	declare @tNow float = CONVERT (
								   float,
								   datepart(hh,getdate())*10000 + 
								   datepart(mi, getdate())*100 +
								   datepart(ss, getdate())
								   ); -- Time now as held by JDE

	insert into atmp.F0401								   
	select distinct
			ABAN8 AS A6AN8,
			N'' COLLATE DATABASE_DEFAULT AS A6APC,
			VF.MCUP COLLATE DATABASE_DEFAULT AS A6MCUP,
			VF.OBAP COLLATE DATABASE_DEFAULT AS A6OBAP,
			VF.AIDP COLLATE DATABASE_DEFAULT AS A6AIDP,
			N'' COLLATE DATABASE_DEFAULT AS A6KCOP,
			CAST(0 AS FLOAT) AS A6DCAP,
			N'' COLLATE DATABASE_DEFAULT AS A6DTAP,
			N'' COLLATE DATABASE_DEFAULT AS A6CRRP,
			N'' COLLATE DATABASE_DEFAULT AS A6TXA2,
			N'' COLLATE DATABASE_DEFAULT AS A6EXR2,
			N'N' COLLATE DATABASE_DEFAULT AS A6HDPY,
			N'' COLLATE DATABASE_DEFAULT AS A6TXA3,
			N'' COLLATE DATABASE_DEFAULT AS A6EXR3,
			CAST(0 AS FLOAT) AS A6TAWH,
			CAST(0 AS FLOAT) AS A6PCWH, 
			case V.TermsCode
				when '00' then N'01'
				when '01' then N'D1'  -- error
				when '02' then N'13'
				when '05' then N'1.6'
				when '07' then N'N7'
				when '10' then N'N10' 
				when '11' then N'1/1' 
				when '14' then N'N14'
				when '15' then N'N15'
				when '20' then N'N20'
				when '21' then N'2/1'
				when '30' then N'N30'
				when '35' then N'235'
				when '36' then N'N36'
				when '45' then N'N45'
				when '46' then N'235'
				when '60' then N'N60'
				when '90' then N'N90'
				else N'EE' 			  -- error
			end COLLATE Latin1_General_CI_AS_WS as A6TRAP,
			N'N' COLLATE DATABASE_DEFAULT AS A6SCK,
			VF1.PYIN COLLATE DATABASE_DEFAULT AS A6PYIN,
			CAST(0 AS FLOAT) AS A6SNTO,
			N'N' COLLATE DATABASE_DEFAULT AS A6AB1,
			CAST(0 AS FLOAT) AS A6FLD,
			N'6' COLLATE DATABASE_DEFAULT AS A6SQNL,
			N'USD' COLLATE DATABASE_DEFAULT AS A6CRCA,
			CAST(0 AS FLOAT) AS A6AYPD,
			CAST(0 AS FLOAT) AS A6APPD,
			CAST(0 AS FLOAT) AS A6ABAM,
			CAST(0 AS FLOAT) AS A6ABA1,
			CAST(0 AS FLOAT) AS A6APRC,
			CAST(0 AS FLOAT) AS A6MINO,
			CAST(0 AS FLOAT) AS A6MAXO,
			CAST(0 AS FLOAT) AS A6AN8R,
			N'X' COLLATE DATABASE_DEFAULT AS A6BADT,
			N'' COLLATE DATABASE_DEFAULT AS A6CPGP,
			N'' COLLATE DATABASE_DEFAULT AS A6ORTP,
			N'' COLLATE DATABASE_DEFAULT AS A6INMG,
			N'' COLLATE DATABASE_DEFAULT AS A6HOLD,
			N'' COLLATE DATABASE_DEFAULT AS A6ROUT,
			N'' COLLATE DATABASE_DEFAULT AS A6STOP,
			N'' COLLATE DATABASE_DEFAULT AS A6ZON,
			CAST(0 AS FLOAT) AS A6ANCR,
			CAST(0 AS FLOAT) AS A6CARS,
			N'' COLLATE DATABASE_DEFAULT AS A6DEL1,
			N'' COLLATE DATABASE_DEFAULT AS A6DEL2,
			CAST(0 AS FLOAT) AS A6LTDT,
			N'' COLLATE DATABASE_DEFAULT AS A6FRTH,
			CAST(1 AS FLOAT) AS A6INVC,
			N'Y' COLLATE DATABASE_DEFAULT AS A6PLST,
			N'' COLLATE DATABASE_DEFAULT AS A6WUMD,
			N'' COLLATE DATABASE_DEFAULT AS A6VUMD,
			N'' COLLATE DATABASE_DEFAULT AS A6PRP5,
			N'' COLLATE DATABASE_DEFAULT AS A6EDPM,
			N'' COLLATE DATABASE_DEFAULT AS A6EDCI,
			N'' COLLATE DATABASE_DEFAULT AS A6EDII,
			CAST(0 AS FLOAT) AS A6EDQD,
			CAST(0 AS FLOAT) AS A6EDAD,
			N'' COLLATE DATABASE_DEFAULT AS A6EDF1,
			N'E' COLLATE DATABASE_DEFAULT AS A6EDF2,
			N'' COLLATE DATABASE_DEFAULT AS A6VI01,
			N'' COLLATE DATABASE_DEFAULT AS A6VI02,
			N'' COLLATE DATABASE_DEFAULT AS A6VI03,
			N'' COLLATE DATABASE_DEFAULT AS A6VI04,
			N'' COLLATE DATABASE_DEFAULT AS A6VI05,
			N'1' COLLATE DATABASE_DEFAULT AS A6MNSC,
			N'N' COLLATE DATABASE_DEFAULT AS A6ATO,
			N'N' COLLATE DATABASE_DEFAULT AS A6RVNT,
			N'' COLLATE DATABASE_DEFAULT AS A6URCD,
			0 AS A6URDT,
			CAST(0 AS FLOAT) AS A6URAT,
			CAST(0 AS FLOAT) AS A6URAB,
			N'' COLLATE DATABASE_DEFAULT AS A6URRF,
			@user COLLATE DATABASE_DEFAULT AS A6USER,
			@pid COLLATE DATABASE_DEFAULT AS A6PID,
			@jobn COLLATE DATABASE_DEFAULT AS A6JOBN,
			@jToday AS A6UPMJ,
			CAST(@tnow AS FLOAT) AS A6UPMT,
			N'' COLLATE DATABASE_DEFAULT AS A6ASN,
			N'' COLLATE DATABASE_DEFAULT AS A6CRMD,
			N'N' COLLATE DATABASE_DEFAULT AS A6AVCH,
			N'' COLLATE DATABASE_DEFAULT AS A6ATRL
	from 
		atmp.F0101
		left join dbo.ods_VendorFlatFile as VF on ABALKY = VF.ALKY COLLATE DATABASE_DEFAULT and VF.MCUP is not NULL
		left join dbo.ods_VendorFlatFile as VF1 on ABALKY = VF1.ALKY COLLATE DATABASE_DEFAULT and VF1.PYIN is not NULL
		left join dbo.ods_AP_Vendor as V on ABALKY = V.VendorNo COLLATE DATABASE_DEFAULT
	where 
		ABAT1 = N'V3'
END

