use SelectoJDE
go
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- ****************************************************************************************
-- Populate JDE's F0911Z1 file with data from the open invoice file
--
-- History: 
-- 29-Jun-2020 R.Lillback Created Initial Version
--  
-- ****************************************************************************************
IF EXISTS(SELECT * FROM SYS.objects WHERE TYPE = 'P' AND name = N'usp_F0911Z1')
	DROP PROCEDURE dbo.usp_F0911Z1
GO

CREATE PROCEDURE dbo.usp_F0911Z1
AS
BEGIN

	SET NOCOUNT ON;

	if object_id(N'tempdb..#F0911Z1') is not null
		drop table #F0911Z1

	CREATE TABLE #F0911Z1(
		[VNEDUS] [nchar](10) NOT NULL,
		[VNEDTY] [nchar](1) NULL,
		[VNEDSQ] [float] NULL,
		[VNEDTN] [nchar](22) NOT NULL,
		[VNEDCT] [nchar](2) NULL,
		[VNEDLN] [float] NOT NULL,
		[VNEDTS] [nchar](6) NULL,
		[VNEDFT] [nchar](10) NULL,
		[VNEDDT] [numeric](18, 0) NULL,
		[VNEDER] [nchar](1) NULL,
		[VNEDDL] [float] NULL,
		[VNEDSP] [nchar](1) NULL,
		[VNEDTC] [nchar](1) NULL,
		[VNEDTR] [nchar](1) NULL,
		[VNEDBT] [nchar](15) NOT NULL,
		[VNEDGL] [nchar](1) NULL,
		[VNEDAN] [float] NULL,
		[VNKCO] [nchar](5) NULL,
		[VNDCT] [nchar](2) NULL,
		[VNDOC] [float] NULL,
		[VNDGJ] [numeric](18, 0) NULL,
		[VNJELN] [float] NULL,
		[VNEXTL] [nchar](2) NULL,
		[VNPOST] [nchar](1) NULL,
		[VNICU] [float] NULL,
		[VNICUT] [nchar](2) NULL,
		[VNDICJ] [numeric](18, 0) NULL,
		[VNDSYJ] [numeric](18, 0) NULL,
		[VNTICU] [float] NULL,
		[VNCO] [nchar](5) NULL,
		[VNANI] [nchar](29) NULL,
		[VNAM] [nchar](1) NULL,
		[VNAID] [nchar](8) NULL,
		[VNMCU] [nchar](12) NULL,
		[VNOBJ] [nchar](6) NULL,
		[VNSUB] [nchar](8) NULL,
		[VNSBL] [nchar](8) NULL,
		[VNSBLT] [nchar](1) NULL,
		[VNLT] [nchar](2) NULL,
		[VNPN] [float] NULL,
		[VNCTRY] [float] NULL,
		[VNFY] [float] NULL,
		[VNFQ] [nchar](4) NULL,
		[VNCRCD] [nchar](3) NULL,
		[VNCRR] [float] NULL,
		[VNHCRR] [float] NULL,
		[VNHDGJ] [numeric](18, 0) NULL,
		[VNAA] [float] NULL,
		[VNU] [float] NULL,
		[VNUM] [nchar](2) NULL,
		[VNGLC] [nchar](4) NULL,
		[VNRE] [nchar](1) NULL,
		[VNEXA] [nchar](30) NULL,
		[VNEXR] [nchar](30) NULL,
		[VNR1] [nchar](8) NULL,
		[VNR2] [nchar](8) NULL,
		[VNR3] [nchar](8) NULL,
		[VNSFX] [nchar](3) NULL,
		[VNODOC] [float] NULL,
		[VNODCT] [nchar](2) NULL,
		[VNOSFX] [nchar](3) NULL,
		[VNPKCO] [nchar](5) NULL,
		[VNOKCO] [nchar](5) NULL,
		[VNPDCT] [nchar](2) NULL,
		[VNAN8] [float] NULL,
		[VNCN] [nchar](8) NULL,
		[VNDKJ] [numeric](18, 0) NULL,
		[VNDKC] [numeric](18, 0) NULL,
		[VNASID] [nchar](25) NULL,
		[VNBRE] [nchar](1) NULL,
		[VNRCND] [nchar](1) NULL,
		[VNSUMM] [nchar](1) NULL,
		[VNPRGE] [nchar](1) NULL,
		[VNTNN] [nchar](1) NULL,
		[VNALT1] [nchar](1) NULL,
		[VNALT2] [nchar](1) NULL,
		[VNALT3] [nchar](1) NULL,
		[VNALT4] [nchar](1) NULL,
		[VNALT5] [nchar](1) NULL,
		[VNALT6] [nchar](1) NULL,
		[VNALT7] [nchar](1) NULL,
		[VNALT8] [nchar](1) NULL,
		[VNALT9] [nchar](1) NULL,
		[VNALT0] [nchar](1) NULL,
		[VNALTT] [nchar](1) NULL,
		[VNALTU] [nchar](1) NULL,
		[VNALTV] [nchar](1) NULL,
		[VNALTW] [nchar](1) NULL,
		[VNALTX] [nchar](1) NULL,
		[VNALTZ] [nchar](1) NULL,
		[VNDLNA] [nchar](1) NULL,
		[VNCFF1] [nchar](1) NULL,
		[VNCFF2] [nchar](1) NULL,
		[VNASM] [nchar](1) NULL,
		[VNBC] [nchar](1) NULL,
		[VNVINV] [nchar](25) NULL,
		[VNIVD] [numeric](18, 0) NULL,
		[VNWR01] [nchar](4) NULL,
		[VNPO] [nchar](8) NULL,
		[VNPSFX] [nchar](3) NULL,
		[VNDCTO] [nchar](2) NULL,
		[VNLNID] [float] NULL,
		[VNWY] [float] NULL,
		[VNWN] [float] NULL,
		[VNFNLP] [nchar](1) NULL,
		[VNOPSQ] [float] NULL,
		[VNJBCD] [nchar](6) NULL,
		[VNJBST] [nchar](4) NULL,
		[VNHMCU] [nchar](12) NULL,
		[VNDOI] [float] NULL,
		[VNALID] [nchar](25) NULL,
		[VNALTY] [nchar](2) NULL,
		[VNDSVJ] [numeric](18, 0) NULL,
		[VNTORG] [nchar](10) NULL,
		[VNREG#] [float] NULL,
		[VNPYID] [float] NULL,
		[VNUSER] [nchar](10) NULL,
		[VNPID] [nchar](10) NULL,
		[VNJOBN] [nchar](10) NULL,
		[VNUPMJ] [numeric](18, 0) NULL,
		[VNUPMT] [float] NULL,
		[VNCRRM] [nchar](1) NULL,
		[VNACR] [float] NULL,
		[VNDGM] [float] NULL,
		[VNDGD] [float] NULL,
		[VNDGY] [float] NULL,
		[VNDG#] [float] NULL,
		[VNDICM] [float] NULL,
		[VNDICD] [float] NULL,
		[VNDICY] [float] NULL,
		[VNDIC#] [float] NULL,
		[VNDSYM] [float] NULL,
		[VNDSYD] [float] NULL,
		[VNDSYY] [float] NULL,
		[VNDSY#] [float] NULL,
		[VNDKM] [float] NULL,
		[VNDKD] [float] NULL,
		[VNDKY] [float] NULL,
		[VNDK#] [float] NULL,
		[VNDSVM] [float] NULL,
		[VNDSVD] [float] NULL,
		[VNDSVY] [float] NULL,
		[VNDSV#] [float] NULL,
		[VNHDGM] [float] NULL,
		[VNHDGD] [float] NULL,
		[VNHDGY] [float] NULL,
		[VNHDG#] [float] NULL,
		[VNDKCM] [float] NULL,
		[VNDKCD] [float] NULL,
		[VNDKCY] [float] NULL,
		[VNDKC#] [float] NULL,
		[VNIVDM] [float] NULL,
		[VNIVDD] [float] NULL,
		[VNIVDY] [float] NULL,
		[VNIVD#] [float] NULL,
		[VNABR1] [nchar](12) NULL,
		[VNABR2] [nchar](12) NULL,
		[VNABR3] [nchar](12) NULL,
		[VNABR4] [nchar](12) NULL,
		[VNABT1] [nchar](1) NULL,
		[VNABT2] [nchar](1) NULL,
		[VNABT3] [nchar](1) NULL,
		[VNABT4] [nchar](1) NULL,
		[VNITM] [float] NULL,
		[VNPM01] [nchar](1) NULL,
		[VNPM02] [nchar](1) NULL,
		[VNPM03] [nchar](1) NULL,
		[VNPM04] [nchar](1) NULL,
		[VNPM05] [nchar](1) NULL,
		[VNPM06] [nchar](1) NULL,
		[VNPM07] [nchar](1) NULL,
		[VNPM08] [nchar](1) NULL,
		[VNPM09] [nchar](1) NULL,
		[VNPM10] [nchar](1) NULL,
		[VNBCRC] [nchar](3) NULL,
		[VNEXR1] [nchar](2) NULL,
		[VNTXA1] [nchar](10) NULL,
		[VNTXITM] [float] NULL,
		[VNACTB] [nchar](10) NULL,
		[VNSTAM] [float] NULL,
		[VNCTAM] [float] NULL,
		[VNAG] [float] NULL,
		[VNAGF] [float] NULL,
		[VNTKTX] [nchar](1) NULL,
		[VNDLNID] [float] NULL,
		[VNCKNU] [nchar](25) NULL,
		[VNBUPC] [nchar](1) NULL,
		[VNAHBU] [nchar](12) NULL,
		[VNEPGC] [nchar](3) NULL,
		[VNJPGC] [nchar](3) NULL,
		[VNRC5] [float] NULL,
		[VNSFXE] [float] NULL,
		[VNOFM] [nchar](1) NULL,
	)

	--
	-- Copy data into the F0911Z1 from the open invoice file
	--
	insert into #F0911Z1
		select 
			N'LEDGINGTON' as VNEDUS,
			N'' as VNEDTY,
			0 as VNEDSQ,
			N'1' as VNEDTN,
			N'' as VNEDCT,
			1 as VNEDLN,
			N'' as VNEDTS,
			N'' as VNEDFT,
			dbo.fn_DateTimeToJulian(GETDATE()) as VNEDDT,
			N'' as VNEDER,
			0 as VNEDDL,
			N'0' as VNEDSP,
			N'' as VNEDTC,
			N'' as VNEDTR,
			N'8023' as VNEDBT,
			N'' as VNEDGL,
			821756 as VNEDAN,
			N'' as VNKCO,
			N'' as VNDCT,
			0 as VNDOC,
			dbo.fn_DateTimeToJulian(GETDATE()) as VNDGJ,
			0 as VNJELN,
			N'' as VNEXTL,
			N'' as VNPOST,
			0 as VNICU,
			N'IB' as VNICUT,
			dbo.fn_DateTimeToJulian(GETDATE()) as VNDICJ,
			dbo.fn_DateTimeToJulian(GETDATE()) as VNDSYJ,
			0 as VNTICU,
			N'' as VNCO,
			N'' as VNANI,
			N'' as VNAM,
			N'' as VNAID,
			N'       91900' as VNMCU,
			N'82000' as VNOBJ,
			N'000' as VNSUB,
			N'' as VNSBL,
			N'' as VNSBLT,
			N'AA' as VNLT,
			0 as VNPN,
			0 as VNCTRY,
			0 as VNFY,
			N'' as VNFQ,
			N'' as VNCRCD,
			0 as VNCRR,
			0 as VNHCRR,
			0 as VNHDGJ,
			cast((Balance * 100) as numeric(15,2)) as VNAA,
			0 as VNU,
			N'' as VNUM,
			N'' as VNGLC,
			N'' as VNRE,
			N'' as VNEXA,
			N'' as VNEXR,
			N'' as VNR1,
			N'' as VNR2,
			N'' as VNR3,
			N'' as VNSFX,
			0 as VNODOC,
			N'' as VNODCT,
			N'' as VNOSFX,
			N'' as VNPKCO,
			N'' as VNOKCO,
			N'' as VNPDCT,
			0 as VNAN8,
			N'' as VNCN,
			0 as VNDKJ,
			0 as VNDKC,
			N'' as VNASID,
			N'' as VNBRE,
			N'' as VNRCND,
			N'' as VNSUMM,
			N'' as VNPRGE,
			N'' as VNTNN,
			N'' as VNALT1,
			N'' as VNALT2,
			N'' as VNALT3,
			N'' as VNALT4,
			N'' as VNALT5,
			N'' as VNALT6,
			N'' as VNALT7,
			N'' as VNALT8,
			N'' as VNALT9,
			N'' as VNALT0,
			N'' as VNALTT,
			N'' as VNALTU,
			N'' as VNALTV,
			N'' as VNALTW,
			N'' as VNALTX,
			N'' as VNALTZ,
			N'' as VNDLNA,
			N'' as VNCFF1,
			N'' as VNCFF2,
			N'' as VNASM,
			N'' as VNBC,
			N'' as VNVINV,
			0 as VNIVD,
			N'' as VNWR01,
			N'' as VNPO,
			N'' as VNPSFX,
			N'' as VNDCTO,
			0 as VNLNID,
			0 as VNWY,
			0 as VNWN,
			N'' as VNFNLP,
			0 as VNOPSQ,
			N'' as VNJBCD,
			N'' as VNJBST,
			N'' as VNHMCU,
			0 as VNDOI,
			N'' as VNALID,
			N'' as VNALTY,
			0 as VNDSVJ,
			N'' as VNTORG,
			0 as VNREG#,
			0 as VNPYID,
			N'' as VNUSER,
			N'' as VNPID,
			N'' as VNJOBN,
			0 as VNUPMJ,
			0 as VNUPMT,
			N'' as VNCRRM,
			0 as VNACR,
			0 as VNDGM,
			0 as VNDGD,
			0 as VNDGY,
			0 as VNDG#,
			0 as VNDICM,
			0 as VNDICD,
			0 as VNDICY,
			0 as VNDIC#,
			0 as VNDSYM,
			0 as VNDSYD,
			0 as VNDSYY,
			0 as VNDSY#,
			0 as VNDKM,
			0 as VNDKD,
			0 as VNDKY,
			0 as VNDK#,
			0 as VNDSVM,
			0 as VNDSVD,
			0 as VNDSVY,
			0 as VNDSV#,
			0 as VNHDGM,
			0 as VNHDGD,
			0 as VNHDGY,
			0 as VNHDG#,
			0 as VNDKCM,
			0 as VNDKCD,
			0 as VNDKCY,
			0 as VNDKC#,
			0 as VNIVDM,
			0 as VNIVDD,
			0 as VNIVDY,
			0 as VNIVD#,
			N'' as VNABR1,
			N'' as VNABR2,
			N'' as VNABR3,
			N'' as VNABR4,
			N'' as VNABT1,
			N'' as VNABT2,
			N'' as VNABT3,
			N'' as VNABT4,
			0 as VNITM,
			N'' as VNPM01,
			N'' as VNPM02,
			N'' as VNPM03,
			N'' as VNPM04,
			N'' as VNPM05,
			N'' as VNPM06,
			N'' as VNPM07,
			N'' as VNPM08,
			N'' as VNPM09,
			N'' as VNPM10,
			N'' as VNBCRC,
			N'' as VNEXR1,
			N'' as VNTXA1,
			0 as VNTXITM,
			N'' as VNACTB,
			0 as VNSTAM,
			0 as VNCTAM,
			0 as VNAG,
			0 as VNAGF,
			N'' as VNTKTX,
			0 as VNDLNID,
			N'' as VNCKNU,
			N'' as VNBUPC,
			N'' as VNAHBU,
			N'' as VNEPGC,
			N'' as VNJPGC,
			0 as VNRC5,
			0 as VNSFXE,
			N'' as VNOFM
		from dbo.ods_AR_OpenInvoice
		where Balance <> 0

	--
	-- Set each transaction as a unique ID
	--
	update x
		set x.VNEDTN = x.NewEDTN
	from (
		select 
			VNEDTN,
			ROW_NUMBER() over (order by VNEDAN asc) as NewEDTN
		from #F0911Z1
	) as x

	--
	-- Copy things into a table to be copied into JDE
	--
	insert into atmp.F0911Z1
		select * from #F0911Z1

	drop table #F0911Z1
end
go